# Time of day when alarms should be played
alarms:
  - hour: 7
    minute: 0
    weekdays:
      - Mon
      - Tue
      - Wed
      - Thu
      - Fri
  - hour: 9
    minute: 30
    weekdays:
      - Sat
      - Sun

# Path to the alarm audio
# Currently only supports single file. Will support directory soon TM.
audio_path: '~/hacky-clock-alarm/'
